spring.application.name=soap-messenger-server

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:soap_messenger}
spring.datasource.username=${DB_USERNAME:soap_messenger}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
